language: node_js
node_js: "node"
env:
  global:
    NEO4J_TEST_PORT=7687
    NEO4J_TEST_USER=neo4j
    NEO4J_TEST_PASS=test
  matrix:
    - NEO4J_VERSION="3.1.7"
    - NEO4J_VERSION="3.2.8"
    - NEO4J_VERSION="3.3.1"

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password test

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: report coverage
      env:
        - NEO4J_VERSION="3.3.1"
      script: npm run coveralls
